server:
  shutdown: graceful
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
spring:
  lifecycle:
    timeout-per-shutdown-phase: 1m
  profiles:
    active: dev
    include:
      - base-addi
      - email
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: ALWAYS
  jpa:
    show-sql: true
#  cache:
#    type: redis
#  redis:
#    host: 127.0.0.1
#    port: 6379
  output:
    ansi:
      enabled: ALWAYS
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
logging:
  level:
    com.yejin.exam.wbook: debug

#spring.batch.initialize-schema: always
#custom:
#  genFileDirPath: c:/temp/app10

custom:
  site:
    name: wbook
    baseUrl: "http://localhost:8080"


